### PR TITLE
Add way for user to specify a min and max length of a tag

### PR DESCRIPTION
**Pull request by makeupsomething**
I have added a way for a user to specify the min and max length of a tag

### CODE REVIEW

**Comment by tristanbes** [comment]
Thanks for your contribution.

How did you find our fork ?

**Comment by makeupsomething** [comment]
I am using it in a project for work and this min/max length thing was actually something necessary for us.

If you don't think you need it as a feature feel free close this PR 👍

**Comment by Kocal** [comment]
Thanks your for this contribution! :tada:
So we are not the only one to use this fork... :open_mouth: :rofl:  



Also, do you think it is possible to make the length configurable on the [documentation](https://yproximite.github.io/better-vue-input-tag/) please? 
That would be nice to have one or two `<input type="number">` to configure min and max length.

Thanks :slightly_smiling_face:

**Comment by Kocal** [comment]
Thanks @makeupsomething. :tada:

**Comment by makeupsomething** [comment]
@Kocal Thanks! My first opens source PR! 🎉

**Comment by tristanbes** [comment]
Congratulation, hope it's the first among many more !

**Pull request merged**
